#!/bin/bash

#SBATCH --account jhfhmm
#SBATCH --time 0-12:00:00
#SBATCH --mem=20G
#SBATCH --cpus-per-task 11
#SBATCH --ntasks 1
#SBATCH --nodes 1

plotFingerprint -b /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_H3K4me3_R1_AnaTelo-phase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_H3K4me3_R2_AnaTelo-phase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_INPUT_R1_AnaTelo-phase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_INPUT_R2_AnaTelo-phase_DM6_sorted_UNIQUEREADS.bam --labels  H3K4me3_R1 H3K4me3_R2 Input_R1 Input_R2 --plotFile RPE1_AnaTelo-phase_fingerprint_DM6.png --outQualityMetrics RPE1_AnaTelo-phase_DM6_FingerprintMetrics -p 11
plotFingerprint -b /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_H3K4me3_R1_Interphase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_H3K4me3_R2_Interphase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_INPUT_R1_Interphase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_INPUT_R2_Interphase_DM6_sorted_UNIQUEREADS.bam --labels  H3K4me3_R1 H3K4me3_R2 Input_R1 Input_R2 --plotFile RPE1_Interphase_fingerprint_DM6.png --outQualityMetrics RPE1_Interphase_DM6_FingerprintMetrics -p 11
plotFingerprint -b /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_H3K4me3_R1_Prometaphase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_H3K4me3_R2_Prometaphase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_INPUT_R1_Prometaphase_DM6_sorted_UNIQUEREADS.bam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/052-uniquereads_sambamba_DM6/rpe1_INPUT_R2_Prometaphase_DM6_sorted_UNIQUEREADS.bam --labels  H3K4me3_R1 H3K4me3_R2 Input_R1 Input_R2 --plotFile RPE1_Prometaphase_fingerprint_DM6.png --outQualityMetrics RPE1_Prometaphase_DM6_FingerprintMetrics -p 11

#This script will create a plot comparing enrichment of all datasets from Kang for rpe1 cells (DM6)

#Runner script not needed as only making 1 plot from this script and all names are given here

#When running need to do in terminal: sbatch SCRIPT_NAME.sh
