#!/bin/bash

#SBATCH --account jhfhmm
#SBATCH --time 0-12:00:00
#SBATCH --mem=20G
#SBATCH --cpus-per-task 11
#SBATCH --ntasks 1
#SBATCH --nodes 1

FILENAME=$1
genomeCoverageBed -bg -ibam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/04.2-samTools/sorted_bam_files/${FILENAME}_sorted.bam -g /nobackup/proj/jhfhmm/RHIANNON/GRCh38_RefGenome/genome.info > /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.2-bamToBigWig/bedgraph_files/${FILENAME}_GRCh38.bedgraph
bedSort /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.2-bamToBigWig/bedgraph_files/${FILENAME}_GRCh38.bedgraph /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.2-bamToBigWig/bedgraph_files/${FILENAME}_SORTED_GRCh38.bedgraph
bedGraphToBigWig /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.2-bamToBigWig/bedgraph_files/${FILENAME}_SORTED_GRCh38.bedgraph /nobackup/proj/jhfhmm/RHIANNON/GRCh38_RefGenome/genome.info /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.2-bamToBigWig/${FILENAME}_GRCh38.bigwig
rm /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.2-bamToBigWig/bedgraph_files/${FILENAME}_GRCh38.bedgraph
Runner Script 
sbatch 06-bamToBigWig.sh rpe1_H3K4me3_R1_Interphase
sbatch 06-bamToBigWig.sh rpe1_H3K4me3_R2_Interphase
sbatch 06-bamToBigWig.sh rpe1_H3K4me3_R1_Prometaphase
sbatch 06-bamToBigWig.sh rpe1_H3K4me3_R2_Prometaphase
sbatch 06-bamToBigWig.sh rpe1_H3K4me3_R1_AnaTelo-phase
sbatch 06-bamToBigWig.sh rpe1_H3K4me3_R2_AnaTelo-phase
sbatch 06-bamToBigWig.sh rpe1_INPUT_R1_Interphase
sbatch 06-bamToBigWig.sh rpe1_INPUT_R1_Prometaphase
sbatch 06-bamToBigWig.sh rpe1_INPUT_R1_AnaTelo-phase
sbatch 06-bamToBigWig.sh rpe1_INPUT_R2_Interphase
sbatch 06-bamToBigWig.sh rpe1_INPUT_R2_Prometaphase
sbatch 06-bamToBigWig.sh rpe1_INPUT_R2_AnaTelo-phase

