#!/bin/bash

#SBATCH --account jhfhmm
#SBATCH --time 0-12:00:00
#SBATCH --mem=20G
#SBATCH --cpus-per-task 11
#SBATCH --ntasks 1
#SBATCH --nodes 1

FILENAME=$1
genomeCoverageBed -bg -ibam /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/04.3-samTools_DM6/sorted_bam_files/${FILENAME}_DM6_sorted.bam -g /nobackup/proj/jhfhmm/RHIANNON/drosophila_m6_refgenome/refGene > /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.3-bedGraphToBigWig_DM6/bedgraph_files/${FILENAME}_DM6.bedgraph
bedSort /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.3-bedGraphToBigWig_DM6/bedgraph_files/${FILENAME}_DM6.bedgraph /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.3-bedGraphToBigWig_DM6/bedgraph_files/${FILENAME}_DM6_sorted.bedgraph
bedGraphToBigWig /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.3-bedGraphToBigWig_DM6/bedgraph_files/${FILENAME}_DM6_sorted.bedgraph /nobackup/proj/jhfhmm/RHIANNON/drosophila_m6_refgenome/refGene /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.3-bedGraphToBigWig/${FILENAME}_DM6.bigwig
rm /nobackup/proj/jhfhmm/RHIANNON/kang_data/rpe1/05.3-bedGraphToBigWig_DM6/bedgraph_files/${FILENAME}_DM6.bedgraph
Runner Script 
sbatch 05-bamToBigWig.sh rpe1_H3K4me3_R1_Interphase
sbatch 05-bamToBigWig.sh rpe1_H3K4me3_R2_Interphase
sbatch 05-bamToBigWig.sh rpe1_H3K4me3_R1_Prometaphase
sbatch 05-bamToBigWig.sh rpe1_H3K4me3_R2_Prometaphase
sbatch 05-bamToBigWig.sh rpe1_H3K4me3_R1_AnaTelo-phase
sbatch 05-bamToBigWig.sh rpe1_H3K4me3_R2_AnaTelo-phase
sbatch 05-bamToBigWig.sh rpe1_INPUT_R1_Interphase
sbatch 05-bamToBigWig.sh rpe1_INPUT_R1_Prometaphase
sbatch 05-bamToBigWig.sh rpe1_INPUT_R1_AnaTelo-phase
sbatch 05-bamToBigWig.sh rpe1_INPUT_R2_Interphase
sbatch 05-bamToBigWig.sh rpe1_INPUT_R2_Prometaphase
sbatch 05-bamToBigWig.sh rpe1_INPUT_R2_AnaTelo-phase
